### ISSUE TITLE
Cleanup storeNewDetails

### ISSUE THREAD

**Issue by 0WN463** [CS2113-AY1819S1-F10-1/main#140]
![image](https://user-images.githubusercontent.com/35750423/47167346-d9c11200-d330-11e8-9c0f-16612804a553.png)
Seems a bit spaghetti to do so many null checks, though I'm sure ya planning to work on it later.

Also, I'd suggest using enums for the keys rather than a string, for a more robust system

**Comment by micklwl** [comment]
Under #143

**Comment by micklwl** [comment]
thinking of using optional somewhere for this to remove all the null checks. why enum though

**Comment by 0WN463** [comment]
Use enum cause it enforces spelling. So you won't have bugs due to referring "examstartTime" instead of "examStartTime".
