### ISSUE TITLE
Clearing while logged in is allowed

### ISSUE THREAD

**Issue by 0WN463** [CS2113-AY1819S1-F10-1/main#160]

**Comment by 0WN463** [comment]
Solved in #158

**Comment by 0WN463** [comment]
@micklwl you can confirm that this if fixed in the latest jar

**Comment by micklwl** [comment]
Using an admin account to clear is not possible. I think there is a need to either log the person out automatically, if the person attempting to clear is admin, or tell the user that he has to log out and raise privilege to admin to clear. Preferably, the first option.

**Comment by 0WN463** [comment]
I would argue against the first option though. Cause that would ensure that the person is intentionally clearing the addressbook and should know that his account will be gone.

**Comment by micklwl** [comment]
In that case, it needs to be specified that the user has to log out.

**Comment by 0WN463** [comment]
Solved in #207 
@micklwl 
To be confirmed
