### ISSUE TITLE
Fees Command Bug 

### ISSUE THREAD

**Issue by Meg1456** [CS2113-AY1819S1-F10-1/main#173]
Viewfees Command
When you add a new person to the address book, the fees is initialised to 0 (which is good), but date is also initialised to 0 (doesn't make sense logically. Possible to initialise to current date instead?) 

Listdue Command
The new person added to address book is automatically put under this function even though I didn't edit their fees yet (i.e. fee is shown to be 0, but they are still under due list).

**Comment by micklwl** [comment]
Negative fees value should error message that it needs to be 2dp.
