### ISSUE TITLE
{private Fees: 0.00 / 00-00-0000} showing after adding person to exam

### ISSUE THREAD

**Issue by cs2113-bot-feedback** [CS2113-AY1819S1-F10-1/main#195]
**Describe the bug**
After adding a person there is information in the text box of stuff that is not declared in the user guide (private fees)

**To Reproduce**
1. Run the jar file
2. Add person to exam according to instructions
3. See the box with info text
4. See line {private Fees: 0.00 / 00-00-0000}

**Expected behavior**
I expected to only see the information about the person and exam

**Screenshots**
![image](https://user-images.githubusercontent.com/42614268/47907370-16127780-dec6-11e8-90f7-1bc35cd5b13a.png)

<hr>

**Reported by:** @t0roloco
**Severity:** Not Specified

<sub>[original: nusCS2113-AY1819S1/pe-1#412]</sub>

**Comment by lucdx** [comment]
@micklwl Should I edit and omit fees in your print after adding exam?? If so then I assign myself! Just not sure if i should touch abit of your stuff

**Comment by micklwl** [comment]
The reason that it’s printing it’s because it is part of print all.

**Comment by lucdx** [comment]
Yeah as in do u want to make something that omits fees for this? Cuz print all is required for like viewall etc right. Or I can make also

**Comment by lucdx** [comment]
Or should we leave it..., cuz technically its info about the Person LOL

**Comment by micklwl** [comment]
The issue is actually that the user does not know there is a fees field part of person.

**Comment by micklwl** [comment]
Duplicate of #190
