### ISSUE TITLE
AboutUs is outdated

### ISSUE THREAD

**Issue by 0WN463** [CS2113-AY1819S1-F10-1/main#204]
> What’s in Version 1.3
> 
> A simple GUI added to replace the Text UI.
> 
> A Logic class added together with a LogicTest class.
> 
> Appendices added to Developer Guide
> 
> 5 Features added from each team member listed below
> 
> Allowing increasing privileges for users.
> 
> Viewing of student’s overall attendance.
> 
> Adding of grades to students.
> 
> Keying and viewing of fees of students by administrators.
> 
> Ability to add and store new exam details.

This seems horribly outdated. Perhaps we should discuss as a group as to what to list here?

**Comment by 0WN463** [comment]
@lucdx 
I thought ya said it's updated in your PR?

**Comment by lucdx** [comment]
Eh I think i needa make another PR

**Comment by lucdx** [comment]
Cuz i seperated code from Docu
