### ISSUE TITLE
Reposense issues

### ISSUE THREAD

**Issue by okkhoy** [CS2113-AY1819S1-F10-1/main#208]
@meisbokai 's contributions are not recorded in the latest reposense run

![image](https://user-images.githubusercontent.com/1023494/47977672-725ade80-e0f4-11e8-8d51-87bafbfc9e92.png)

**Comment by eugenepeh** [comment]
Hi, 

This is from the RepoSense team.

https://github.com/CS2113-AY1819S1-F10-1/main/blob/b62359aba3fd1826a36d6c2a570e3589a93aff12/_reposense/config.json#L6

Simply remove the line `	"ignoreCommitList": [""],` if you guys do not have a commit to ignore, should resolve this issue.

Thanks!

**Comment by micklwl** [comment]
Resolved in #218
