### ISSUE TITLE
Logout flow

### ISSUE THREAD

**Issue by micklwl** [CS2113-AY1819S1-F10-1/main#216]
1. Raise privilege to admin. 
2. You can perform logout command and reset back to basic privilege and status message displays "Logged out!".
However, user was never logged in.
Maybe have some other checks or other messages.

**Comment by micklwl** [comment]
Hence, change the message for raiseprivilegecommand?

**Comment by 0WN463** [comment]
But we never had the term "super admin" at all. And logging in without a actual account sounds weird.
Also, the UG says 
> Logs out of the current account, provided there is privilege or account to relinquish.

Since there is privilege to relinquish, you can "log out"

**Comment by micklwl** [comment]
Hm. I guess its a bit late but perhaps we could have make a super admin account instead.

**Comment by micklwl** [comment]
Ah well too late for such changes.
