### ISSUE TITLE
FINAL TESTING: Documentation Errors

### ISSUE THREAD

**Issue by Meg1456** [CS2113-AY1819S1-F10-1/main#232]

**Comment by Meg1456** [comment]
List Statistics and List Assessment Commands should have User picture (for privilege) in the UG. Currently it is the tutor pic.

**Comment by meisbokai** [comment]
> 
> 
> List Statistics and List Assessment Commands should have User picture (for privilege) in the UG. Currently it is the tutor pic.

User picture? Do you mean basic or admin?
