### ISSUE TITLE
[Assessment] addgrades/addstatistics asking to run list command to generate list of assessments.

### ISSUE THREAD

**Issue by micklwl** [CS2113-AY1819S1-F10-1/main#258]

**Comment by 0WN463** [comment]
Inside the App

**Comment by Meg1456** [comment]
@micklwl I check this and I dont find any problem with the message. Can you write the steps to duplicate error? Or send a screenshot to make the issue clearer please

**Comment by 0WN463** [comment]
![image](https://user-images.githubusercontent.com/35750423/48315153-a6ab2f00-e60d-11e8-945b-b98af7e2b0e7.png)

**Comment by Meg1456** [comment]
Ooh ok! Got it, will change thanks
