### ISSUE TITLE
Final submission Requirements met

### ISSUE THREAD

**Issue by 0WN463** [CS2113-AY1819S1-F10-1/main#281]
![image](https://user-images.githubusercontent.com/35750423/48315451-5209b300-e611-11e8-9c86-9aa43e8e648e.png)

#276 V1.4 release
#277 jar
#278 UG
#279 DG
#280 Website

#282 Milestone

To confirm every issue is solved before closing this

**Comment by meisbokai** [comment]
Can we comment here if we have submitted the PPP?
Bokai

**Comment by 0WN463** [comment]
Sure. But just know that I've no intention of chasing for it
