### ISSUE TITLE
Remove unused things in travis.yml and build.gradle

### ISSUE THREAD

**Issue by micklwl** [CS2113-AY1819S1-F10-1/main#47]
@0WN463
https://github.com/CS2113-AY1819S1-F10-1/main/blob/d237ac75e433e152e12000c0866794e6507cbf34/.travis.yml#L7
remove the copyDummySearchPage pls.

https://github.com/CS2113-AY1819S1-F10-1/main/blob/d237ac75e433e152e12000c0866794e6507cbf34/build.gradle#L172-L188
I believe the first has to do with the repetition of the docs, the second is for DummySearchPage which we are not using.

**Comment by micklwl** [comment]
My code is failing travis in this as I believe its trying to check for the lines/files which I have deleted

**Comment by 0WN463** [comment]
Merged, though kinda wanted to keep it in case we wanted to show our AboutUs in the program, but kinda feels like a mid-summer dream
